version: '3.8'

services:
  gpt-chat-app:
    image: gpt2-server
    container_name: gpt-chat-server
    ports:
      - "7137:7137"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=all

    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7137/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - gpt-network

  # Optional: Redis for session management or caching
  # redis:
  #   image: redis:7-alpine
  #   container_name: gpt-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped
  #   networks:
  #     - gpt-network

  # Optional: Nginx reverse proxy
  # nginx:
  #   image: nginx:alpine
  #   container_name: gpt-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     # - ./ssl:/etc/nginx/ssl:ro  # For SSL certificates
  #   depends_on:
  #     - gpt-chat-app
  #   restart: unless-stopped
  #   networks:
  #     - gpt-network


networks:
  gpt-network:
    driver: bridge
